#!/bin/bash
sudo ./cgmemtime --setup -g sudo --perm 775
./cgmemtime node "./fib/fib.js"
./cgmemtime node "./merge/merge.js"
./cgmemtime node "./radix/radix.js"
echo "--------------------------------------------"
echo "--------------------------------------------"
echo "--------------------------------------------"
./cgmemtime fib/fib.o
./cgmemtime merge/merge.o
./cgmemtime radix/radix.o
echo "--------------------------------------------"
echo "--------------------------------------------"
echo "--------------------------------------------"
./cgmemtime node "./fib/index.js"
./cgmemtime node "./merge/index.js"
./cgmemtime node "./radix/index.js"